Tensors
- similar to Numpy's ndarrays, except the tensors can run on GPUs or other hardware accelerators
- TENSORS and NUMPY ARRAYS can often share the same underlying memory, eliminating the need to copy data
- Tensors are optimized for automatic differentiation

In [42]:
import torch 
import numpy as np

# Initializing a Tensor

In [43]:
# directly from data

data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [44]:
# from a NumPy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [45]:
# from another tensor
x_ones = torch.ones_like(x_data) # x_data 구조로 1로 채우기
print(f'One Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f'Random Tensor: \n {x_rand} \n')

One Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8347, 0.1600],
        [0.8816, 0.4103]]) 



In [46]:
# with random or constant values:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(f'Random Tensor: \n {rand_tensor} \n')

ones_tensor = torch.ones(shape)
print(f'Ones Tensor: \n {ones_tensor} \n')

zeros_tensor = torch.zeros(shape)
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.1063, 0.2544, 0.5069],
        [0.3008, 0.3399, 0.8020]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# Attributes of a Tensor
- shape
- dtype
- the device on which the tensor is stored

In [47]:
tensor = torch.rand(3,4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

- 산술, 선형 대수, 행렬 곱셈, 샘플릳 등
https://pytorch.org/docs/stable/torch.html
- each of the operations can be run on the GPU
- by default, tensors are created on the CPU -> need to move tensors to the GPU using *.to* method

In [48]:
# move the tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [49]:
tensor = tensor.to("cuda")
tensor.device

device(type='cuda', index=0)

In [50]:
# standard numpy-like indexing and slicing

tensor = torch.ones(4, 4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [51]:
tensor[:,1] = 0 # 첫번째 열 0으로 치환하기
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [52]:
# joinng tensors
# torch.cat : concatenate a sequence of tensors along a given dimension
# torch.stack -> torch.cat과 비슷하지만 약간 다르게 기능

t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [53]:
# arithmetic operations

# this computes the matrix multiplication between two tensors. 
# y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
print(y1,'\n')

y2 = tensor.matmul(tensor.T)
print(y2,'\n')

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [54]:
# this computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
print('\n', z2, '\n')

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [55]:
# single-element tensors
print(f'tensor: {tensor} \n')
agg = tensor.sum()
print(f'agg: {agg}  type: {type(agg)} \n')

# using item(): convert a tensor with one value to a Python numerical value
agg_item = agg.item()
print(f'agg_item: {agg_item}   type: {type(agg_item)}')

tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

agg: 12.0  type: <class 'torch.Tensor'> 

agg_item: 12.0   type: <class 'float'>


In [56]:
# in-place operation 
print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

# operations that store the result into the operand are called in-place.
# they are denoted by a _ suffix
# x.copy_(y)
# x.t_()

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy

## Tensor to Numpy array

In [57]:
t = torch.ones(5)
print('t:', t)

n = t.numpy()
print('n:', n)

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [58]:
# a change in the tensor reflects in the NumPy array

t.add_(1)
print('t:', t)
print('n:', n)

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [59]:
n = np.ones(5)
t = torch.from_numpy(n)
print('n:', n)
print('t:', t)

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [60]:
# changes in the NumPy array reflects in the tensor
np.add(n, 1, out=n)
print('n:', n)
print('t:', t)

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
